---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: microsoft_CheckProvisioned
    inherits: 
    description: 
  fields:
  - execute:
      value: microsoft_CheckProvisioned
