---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: service_template_provision_task_Complete
    inherits: 
    description: 
  fields:
  - method1:
      value: service_template_provision_task_Complete
